### ISSUE TITLE
Why Lv different?

### ISSUE THREAD

**Issue by hap0328** [Owyn/talents_info#1]
<a href="https://imgur.com/fgaRfuj"><img src="https://i.imgur.com/fgaRfuj.jpg" title="source: imgur.com" /></a>

**Comment by Reny900** [comment]
thats the differnce between TOTAL EP and level
LEVEL ≠ TOTAL EP
to understand this go [here](https://docs.google.com/spreadsheets/d/e/2PACX-1vTy7_5TYA_WUd--cFqYeGFm0mnb9oaCzcar3yH3FgkQD6y-mRD7id9k97ttrMbkjjId8ly-aBWzexZt/pubhtml?gid=5547005&single=true)

**Comment by Owyn** [comment]
added this to readme FAQ
