### ISSUE TITLE
Infinity 

### ISSUE THREAD

**Issue by TerableCoder** [Owyn/talents_info#2]
I hit soft cap yesterday after reset, I logged in today and it says max daily exp is 0 now.
[https://cdn.discordapp.com/attachments/494032094310301716/514543422678499378/unknown.png](url)

**Comment by Owyn** [comment]
`it` is not which says your cap is 0, the `server` says so, for some reason. why? ask BHS devs, module only prints what servers tells your client

**Comment by Owyn** [comment]
Should be fixed with the module update of today, there's another additional way to ask server for daily cap there now.
